name: Tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.13
      
      - name: setup
        run: python setup.py
      
      - name: test board
        run: python tests/test_board.py
