name: Tests

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
      
      - name: test board
        run: tests/test_board.py
